UMC-DEMO-PROJECT/Chat-Sul

.eslintrc.json
.github/ISSUE_TEMPLATE/✅-feature-.md
.github/ISSUE_TEMPLATE/🐞-bug-.md
.prettierrc.json
README.md
eslint.config.js
package.json
src/App.tsx
src/index.css
src/main.tsx
vite.config.ts
yarn.lock

chore: prettier 설치

---

eslint.config.js
package.json
postcss.config.js
src/index.css
src/shared/Router.tsx
tailwind.config.js
yarn.lock

> React-Router-Dom을 이용하여 임시 파일을 구성해놨습니다.
ESLint에 Error가 발생하여 구조 수정했습니다. (AirBnB룰은 적용치 않기로 했습니다.)
>

chore: React-Router-Dom 임시 설정

---

tailwind.config.js

feat: tailwind공용Color설정

---

package.json
src/components/button.tsx
yarn.lock

>#7
> dev에서 pull 받아오고 브랜치 생성해서 버튼 컴포넌트 추가했습니다.
(기존 feat/button 브랜치는 git bash에서 삭제를 해도 github에는 그대로 있길래 직접 지웠습니다. 
git bash로 기존 브랜치가 제대로 삭제가 안되서 _1을 붙이고 새로 생성했어요ㅠㅠ)
>

feat: 버튼 컴포넌트 생성

---

src/assets/lostItem.svg
src/shared/@common/ui/Menu/Menu.tsx
src/shared/@common/ui/Menu/example.tsx
src/shared/@common/ui/Message/Message.tsx
src/shared/@common/ui/Post/Post.tsx
src/shared/@common/ui/Post/example.tsx
src/shared/@common/ui/TopBar/TopBar.tsx
src/shared/@common/ui/TopBar/example.tsx

Menu, Post, TopBar, Message 주석추가했습니다.
>

refactor: Menu, Post, TopBar, Message 주석추가

---

src/index.css

> 
> chore: Layout수정, vite 기본 폰트 css 제거했습니다
>

chore: Layout수정, 폰트수정

---

src/shared/ui/Modal/exampleTwo.tsx
src/shared/ui/Post/Post.tsx

메인div 테두리 패딩 조절, title 폰트 조정
>

refactor: 메인div 테두리 패딩 조절, title 폰트 조정

---

src/shared/ui/Input/Input.tsx

refactor: Input Width 수정

---

src/shared/ui/Post/Post.tsx

refactor:post width랑 border색수정

---

.github/workflows/deploy.yml
src/shared/ui/Input/example.tsx

chore:cicd수정npm->yarn

---

src/components/User/ReserveForm/ReserveFormContainer.tsx

reserve form buttom 위치가 바뀐거 적용했습니다.
>

refactor:reserve form buttom 위치가 바뀐거 적용했습니다.

---

src/components/LostItem/LostItem.tsx
src/index.css
src/shared/ui/TopBar/TopBar.tsx

Feat/lostitem  임시 글꼴 삭제 및 topbar font-weigth 추가

---

src/components/Login/LoginForm.tsx
src/components/Register/RegisterForm.tsx
src/pages/Register/Register.tsx
src/shared/ui/DropDown/example.tsx
src/shared/ui/DropDown/example1.tsx
src/shared/ui/Map/Map.tsx
src/shared/ui/Map/example.tsx
src/shared/ui/Map/example1.tsx

fix: api 수정, 에러 수정 

---

package.json
src/components/Lost/LostInput.tsx
src/components/Lost/Lostlist.tsx
src/pages/User/LostList/LostList.tsx
tsconfig.app.json
vite.config.ts
yarn.lock

> ![image](https://github.com/user-attachments/assets/e3796e08-5589-4524-b6a8-19c319d393be)
>

Feat/lostlist 절대 경로 추가

---

src/pages/User/LostList/LostList.tsx

chore: Pagination 컴포넌트 파일 이름 변경

---

src/pages/Main/kakao.tsx

Feat/lost api 

---

src/components/Owner/ReserveList/ReserveList.tsx
src/components/User/ReserveForm/ui/ReserveFormContainer.tsx
src/components/User/ReserveList/ui/ReserveListContainer.tsx
src/components/User/ReserveSuccess/ReserveSuccessContainer.tsx
src/pages/Main/kakao.tsx

user,owner-reservelist-topbar map경로 수정
>

fix:user,owner-reservelist-topbar

---

src/App.tsx
src/components/Lost/SearchLostList.tsx
src/hooks/useGetSearchInfiniteLostList.ts
src/pages/User/LostList/LostList.tsx
src/pages/User/Shop/userShop.tsx
src/shared/api/lost.tsx
src/shared/type/LostType.ts

> #19 
> ![image](https://github.com/user-attachments/assets/2a744b64-2de5-48bb-b533-fa8d2346cbf4)
>

Feat/lost api 분실물 목록 리스트 및 검색 api 연결

---

src/App.tsx
src/components/Login/LoginForm.tsx
src/components/Lost/Lostlist.tsx
src/components/LostItem/LostItem.tsx
src/components/LostItem/Option.tsx
src/components/LostModify/LostModifyForm.tsx
src/components/Lostwriting/LostWritingForm.tsx
src/context/OwnerContext.tsx
src/pages/Owner/LostItem/LostItem_Owner.tsx
src/pages/Owner/LostModify/LostModify.tsx
src/pages/User/LostItem/LostItem.tsx
src/shared/api/lost.tsx
src/shared/type/LostType.ts
src/shared/ui/Fail/FailedAPI.tsx
src/shared/ui/Post/Post.tsx

> 
- 분실물 등록 API
- 분실물 상세  글 가져오기 API
- 분실물 글 삭제API
- 분실물 수취 상태 변경 API
>

Feat/lost api 분실물 API 연결

---

src/components/Lost/Lostlist.tsx
src/shared/type/LostType.ts

Feat/lost api LostLIst 관련 cicd 에러 코드 수정
